#!/usr/bin/env node

var hookUtils = require("copal-git-hook-utils");

// Only on these branches
var EXEC_ON_BRANCHES = ["master", "dev", "development", "devel", "test"];
hookUtils.branches.exitIfCurrentBranchIsNot( EXEC_ON_BRANCHES, 0 );

// Bump, if necessary
var lastCommits = hookUtils.commits.getCommitSubjectsSince( hookUtils.version.getLastVersionTag() );

if( lastCommits.length === 0 || hookUtils.commitMessage.hasType( lastCommits[0], "VERSION" ) )
  process.exit( 0 );

var biggest = hookUtils.version.getBiggestVersionType( lastCommits );
if( biggest !== "version" ) {
  hookUtils.version.bumpVersion( biggest );
}
